import "./AlternativeCheckers.test.ts"
import "./IsolateRuntimes.test.ts"
import "./Lua.test.ts"
import "./MultipleClassifiers.test.ts"
import "./OnionDiamond.test.ts"
import "./StrictOrdering.test.ts"
