import { Checker, Opinion } from "../Monad/pure.ts"
import { type Chain, MakePartialOrder, type PartialOrder, type PartialOrderKey, QueryPartialOrder } from "./PartialOrder.pure.ts"

// TODO implement Classifier with Reader<filepath, option<T>>
export type Classifier<T> = (filepath: string) => T | null

const classifyAndCompare = <T extends PartialOrderKey>(
	classify: Classifier<T>,
	po: PartialOrder<T>,
): Checker<void> => ([xPath, yPath]: Checker.Deps) => {
		const xClass = classify(xPath)
		const yClass = classify(yPath)

		if (xClass === null || yClass === null)
			return Opinion.Pure<void>(undefined)

		switch (QueryPartialOrder(po, xClass, yClass)) {
			case "<":
			case "=":
				return Opinion.Allow()
			case ">":
			case "?":
				// The error message from esbuild already includes xPath.
				return Opinion.Error(`ClassifyAndCompare: can not depend on ${yPath}`)
		}
	}

/** Create a Checker that first classifies paths according to `classRules` and
 * then compares the resulting classes in the partial order generated by
 * relations `orderRules`. More specifically, for each file with class `X`
 * importing a file of class `Y`, we must have `X < Y` in the partial order.
 *
 * If either the dependent or dependency file don't match any rule in
 * `classRules`, then the returned checker behaves as `Pure(undefined)` (i.e.,
 * it has "no opinion" on whether the file should be allowed or rejected).
 *
 * This function returns a Checker that always errors if `orderRules` induce a
 * cycle. */
export const ClassifyAndCompare = <T extends PartialOrderKey>(
	classify: Classifier<T>,
	chains: Chain<T>[],
): Checker<void> => {
	const po = MakePartialOrder(chains)
	return po === null
		? Checker.Error("ClassifyAndCompare: orderRules induce a cycle")
		: classifyAndCompare(classify, po)
}
