import { Classify } from "../Classify/pure.ts"
import { CurryRev, Flow, Pipe, Option, Reader, Result } from "../Lib/pure.ts"
import { Opinion } from "./Opinion/pure.ts"
import { PartialOrder } from "../Partial_Order/pure.ts"

export * from "./Opinion/pure.ts"

/** Reader environment: Dependent, Dependency */
export type Deps = readonly [string, string]
export type Checker<A> = Reader<Deps, Opinion<A>>

export const Pure = <A>(val: A): Checker<A> => Reader.Pure(Opinion.Pure(val))
export const Allow = <A=never>(): Checker<A> => Reader.Pure(Opinion.Allow())
export const Deny = <A=never>(): Checker<A> => Reader.Asks(Opinion.Deny)
export const Warn = <A=never>(x: string): Checker<A> => Reader.Pure(Opinion.Warn(x))

export const Bind_ = <A, B>(m: Checker<A>, f: (t: A) => Checker<B>) =>
	(d: Deps) => Opinion.Bind(m(d), t => f(t)(d))
export const Bind: {
	<A, B>(m: Checker<A>, f: (t: A) => Checker<B>): Checker<B>
	<A, B>(f: (t: A) => Checker<B>): (m: Checker<A>) => Checker<B>
} = CurryRev(Bind_)

export const Map_ = <A, B>(m: Checker<A>, f: (t: A) => B) =>
	Bind_(m, Flow(f, Pure))
export const Map: {
	<A, B>(m: Checker<A>, f: (t: A) => B): Checker<B>
	<A, B>(f: (t: A) => B): (m: Checker<A>) => Checker<B>
} = CurryRev(Map_)

export const Asks = <A>(f: (d: Deps) => A): Checker<A> =>
	Reader.Asks(Flow(f, Opinion.Pure))
export const Ask: Checker<Deps> =
	Asks(d => d)

export const Then_ = <A, B>(m1: Checker<A>, m2: Checker<B>): Checker<B> =>
	Bind_(m1, _ => m2)
export const Then: {
	<A, B>(m1: Checker<A>, m2: Checker<B>): Checker<B>
	<A, B>(m2: Checker<B>): (m1: Checker<A>) => Checker<B>
} = CurryRev(Then_)

export const When_ = (b: boolean, m: Checker<void>) =>
	b ? m : Pure(undefined)
export const When: {
	(b: boolean, m: Checker<void>): Checker<void>
	(m: Checker<void>): (b: boolean) => Checker<void>
} = CurryRev(When_)

export const AsksWhen_ = (p: (d: Deps) => boolean, m: Checker<void>): Checker<void> =>
	Bind_(Asks(p), When(m))
export const AsksWhen: {
	(p: (d: Deps) => boolean, m: Checker<void>): Checker<void>
	(m: Checker<void>): (p: (d: Deps) => boolean) => Checker<void>
} = CurryRev(AsksWhen_)

export const IfM_ = <A>(mp: Checker<boolean>, m1: Checker<A>, m2: Checker<A>): Checker<A> =>
	Bind_(mp, b => b ? m1 : m2)
export const IfM: {
	<A>(mp: Checker<boolean>, m1: Checker<A>, m2: Checker<A>): Checker<A>
	<A>(m1: Checker<A>, m2: Checker<A>): (mp: Checker<boolean>) => Checker<A>
} = CurryRev(IfM_)

/** Create a Checker that first classifies paths to file extensions,
 * then compares the resulting classes in the partial order generated by
 * relations `orderRules`. More specifically, for each file with class `X`
 * importing a file of class `Y`, we must have `X < Y` in the partial order.
 *
 * If either the dependent or dependency file don't match any rule in
 * `classRules`, then the returned checker behaves as `Pure(undefined)` (i.e.,
 * it has "no opinion" on whether the file should be allowed or rejected).
 */
export const Build = <T extends string>
	(classify: Classify<Classify.GlobExtension<T>>) =>
	(partialOrder: Result<PartialOrder<Classify.GlobExtension<T>>, string>)
	: Result<Checker<void>, string> =>
		Result.Map(partialOrder, po => build(classify, po))

const build = <T extends PartialOrder.Key>(
	classify: Classify<T>,
	po: PartialOrder<T>,
): Checker<void> =>
	([xPath, yPath]: Deps) => Pipe(
		Option.All([classify(xPath), classify(yPath)]),
		Option.Elim(
			Opinion.Pure<void>(undefined),
			([xClass, yClass]): Opinion<never> => {
				switch (PartialOrder.Query(po, xClass, yClass)) {
				case "<":
				case "=":
					return Opinion.Allow()
				case ">":
				case "?":
					return Opinion.Deny([xPath, yPath])
				}
			},
		),
	)
