import { Classify } from "../Classify/pure.ts"
import { Checker } from "../Compare/Checker/pure.ts"
import { Opinion } from "../Compare/Opinion/pure.ts"
import { Option, Pipe, Result } from "../Lib/pure.ts"
import { PartialOrder } from "../Partial_Order/pure.ts"

/** Create a Checker that first classifies paths according to `classRules` and
 * then compares the resulting classes in the partial order generated by
 * relations `orderRules`. More specifically, for each file with class `X`
 * importing a file of class `Y`, we must have `X < Y` in the partial order.
 *
 * If either the dependent or dependency file don't match any rule in
 * `classRules`, then the returned checker behaves as `Pure(undefined)` (i.e.,
 * it has "no opinion" on whether the file should be allowed or rejected).
 */
export const BuildChecker = <T extends string>
	(classify: Classify.Classifier<Classify.Classifier.GlobExtension<T>>) =>
	(partialOrder: Result<PartialOrder<Classify.Classifier.GlobExtension<T>>, string>)
	: Result<Checker<void>, string> =>
		Result.Map(partialOrder, po => buildChecker(classify, po))

const buildChecker = <T extends PartialOrder.Key>(
	classify: Classify.Classifier<T>,
	po: PartialOrder<T>,
): Checker<void> =>
	([xPath, yPath]: Checker.Deps) => Pipe(
		Option.All([classify(xPath), classify(yPath)]),
		Option.Elim(
			Opinion.Pure<void>(undefined),
			([xClass, yClass]): Opinion<never> => {
				switch (PartialOrder.Query(po, xClass, yClass)) {
				case "<":
				case "=":
					return Opinion.Allow()
				case ">":
				case "?":
					return Opinion.Deny([xPath, yPath])
				}
			},
		),
	)
