import { Classify } from "../Classify/pure.ts"
import { Checker } from "../Compare/Checker/pure.ts"
import { Opinion } from "../Compare/Opinion/pure.ts"
import { Option, Pipe } from "../Lib/pure.ts"

import { type Chain, MakePartialOrder, type PartialOrder, type PartialOrderKey, QueryPartialOrder } from "./PartialOrder.pure.ts"

const classifyAndCompare = <T extends PartialOrderKey>(
	classify: Classify.Classifier<T>,
	po: PartialOrder<T>,
): Checker<void> =>
	([xPath, yPath]: Checker.Deps) => Pipe(
		Option.All([classify(xPath), classify(yPath)]),
		Option.Elim(
			Opinion.Pure<void>(undefined),
			([xClass, yClass]): Opinion<never> => {
				switch (QueryPartialOrder(po, xClass, yClass)) {
				case "<":
				case "=":
					return Opinion.Allow()
				case ">":
				case "?":
					// The error message from esbuild already includes xPath.
					// TODO - we could pass a structured error message and
					//        let the plugin convert to string.
					return Opinion.Error(`ClassifyAndCompare: can not depend on ${yPath}`)
				}
			},
		),
	)

/** Create a Checker that first classifies paths according to `classRules` and
 * then compares the resulting classes in the partial order generated by
 * relations `orderRules`. More specifically, for each file with class `X`
 * importing a file of class `Y`, we must have `X < Y` in the partial order.
 *
 * If either the dependent or dependency file don't match any rule in
 * `classRules`, then the returned checker behaves as `Pure(undefined)` (i.e.,
 * it has "no opinion" on whether the file should be allowed or rejected).
 *
 * This function returns a Checker that always errors if `orderRules` induce a
 * cycle. */
export const ClassifyAndCompare = <T extends PartialOrderKey>(
	classify: Classify.Classifier<T>,
	chains: Chain<T>[],
): Checker<void> => Pipe(
	MakePartialOrder(chains),
	Option.ElimLazy(
		() => Checker.Error("ClassifyAndCompare: orderRules induce a cycle"),
		po => classifyAndCompare(classify, po),
	)
)
